on:
  push:
    branches:
      - main
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
        - name: job1
          run: sleep 30

   job2: 
     runs-on: ubuntu-latest
     needs: job1
     steps:
        - name: job2
          run: echo "j"
